export interface CareTemplateSeed {
  speciesName: string;
  careType: string;
  title: string;
  rrule: string;
  monthStart: number;
  monthEnd: number;
  fertilizerName?: string;
  treatmentName?: string;
  priority: string;
}

export const careTemplates: CareTemplateSeed[] = [
  // =====================
  // ЯБЛОНЯ (Apple tree)
  // =====================
  {
    speciesName: 'Яблоня',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Яблоня',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка азотом',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    fertilizerName: 'Мочевина',
    priority: 'HIGH',
  },
  {
    speciesName: 'Яблоня',
    careType: 'FERTILIZE',
    title: 'Подкормка фосфором',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 6,
    fertilizerName: 'Суперфосфат',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Яблоня',
    careType: 'FERTILIZE',
    title: 'Осенняя подкормка калием',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 9,
    fertilizerName: 'Калий сернокислый',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Яблоня',
    careType: 'PRUNE',
    title: 'Весенняя обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Яблоня',
    careType: 'SPRAY',
    title: 'Обработка от парши',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 4,
    monthEnd: 7,
    treatmentName: 'Бордосская жидкость',
    priority: 'HIGH',
  },
  {
    speciesName: 'Яблоня',
    careType: 'SPRAY',
    title: 'Обработка от тли',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Яблоня',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 10,
    priority: 'HIGH',
  },

  // =====================
  // ГРУША (Pear)
  // =====================
  {
    speciesName: 'Груша',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Груша',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Груша',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Груша',
    careType: 'SPRAY',
    title: 'Обработка от болезней',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 7,
    treatmentName: 'Медный купорос',
    priority: 'HIGH',
  },
  {
    speciesName: 'Груша',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 10,
    priority: 'HIGH',
  },

  // =====================
  // ВИШНЯ (Cherry)
  // =====================
  {
    speciesName: 'Вишня',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 8,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Вишня',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Вишня',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Вишня',
    careType: 'SPRAY',
    title: 'Обработка от коккомикоза',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Бордосская жидкость',
    priority: 'HIGH',
  },
  {
    speciesName: 'Вишня',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 7,
    priority: 'HIGH',
  },

  // =====================
  // ТОМАТ (Tomato)
  // =====================
  {
    speciesName: 'Томат',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 6,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Томат',
    careType: 'FERTILIZE',
    title: 'Подкормка комплексная',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Томат',
    careType: 'FERTILIZE',
    title: 'Подкормка калием',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 9,
    fertilizerName: 'Монофосфат калия',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Томат',
    careType: 'PRUNE',
    title: 'Пасынкование',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 8,
    priority: 'HIGH',
  },
  {
    speciesName: 'Томат',
    careType: 'SPRAY',
    title: 'Обработка от фитофтороза',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    treatmentName: 'Фитоспорин-М',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Томат',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Томат',
    careType: 'PLANT',
    title: 'Посев на рассаду',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'CRITICAL',
  },

  // =====================
  // ОГУРЕЦ (Cucumber)
  // =====================
  {
    speciesName: 'Огурец',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Огурец',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Огурец',
    careType: 'SPRAY',
    title: 'Обработка от болезней',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    treatmentName: 'Фитоспорин-М',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Огурец',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Огурец',
    careType: 'PLANT',
    title: 'Посев',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'HIGH',
  },

  // =====================
  // КАРТОФЕЛЬ (Potato)
  // =====================
  {
    speciesName: 'Картофель',
    careType: 'PRUNE',
    title: 'Окучивание',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 7,
    priority: 'HIGH',
  },
  {
    speciesName: 'Картофель',
    careType: 'SPRAY',
    title: 'Обработка от колорадского жука',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    treatmentName: 'Актара',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Картофель',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Картофель',
    careType: 'PLANT',
    title: 'Посадка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Картофель',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 9,
    priority: 'HIGH',
  },

  // =====================
  // КЛУБНИКА (Strawberry)
  // =====================
  {
    speciesName: 'Клубника',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 5,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Клубника',
    careType: 'FERTILIZE',
    title: 'Подкормка весенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Клубника',
    careType: 'FERTILIZE',
    title: 'Подкормка после плодоношения',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Суперфосфат',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Клубника',
    careType: 'SPRAY',
    title: 'Обработка от серой гнили',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 6,
    treatmentName: 'Фитоспорин-М',
    priority: 'HIGH',
  },
  {
    speciesName: 'Клубника',
    careType: 'PRUNE',
    title: 'Обрезка усов',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 8,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Клубника',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 7,
    priority: 'HIGH',
  },

  // =====================
  // СМОРОДИНА ЧЁРНАЯ (Black currant)
  // =====================
  {
    speciesName: 'Смородина чёрная',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Смородина чёрная',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Смородина чёрная',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Смородина чёрная',
    careType: 'SPRAY',
    title: 'Обработка от клеща',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 6,
    treatmentName: 'Фитоверм',
    priority: 'HIGH',
  },
  {
    speciesName: 'Смородина чёрная',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    priority: 'HIGH',
  },

  // =====================
  // ВИНОГРАД СТОЛОВЫЙ (Table grape)
  // =====================
  {
    speciesName: 'Виноград столовый',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'FERTILIZE',
    title: 'Подкормка весенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'FERTILIZE',
    title: 'Подкормка в период созревания',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Монофосфат калия',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'PRUNE',
    title: 'Обрезка осенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'PRUNE',
    title: 'Чеканка побегов',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 8,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'SPRAY',
    title: 'Обработка от милдью',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Бордосская жидкость',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'SPRAY',
    title: 'Обработка от оидиума',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Топаз',
    priority: 'HIGH',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 10,
    priority: 'HIGH',
  },

  // =====================
  // МАЛИНА (Raspberry)
  // =====================
  {
    speciesName: 'Малина',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Малина',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Перегной',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Малина',
    careType: 'PRUNE',
    title: 'Обрезка отплодоносивших побегов',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Малина',
    careType: 'SPRAY',
    title: 'Обработка от вредителей',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Малина',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 8,
    priority: 'HIGH',
  },

  // =====================
  // СЛИВА (Plum)
  // =====================
  {
    speciesName: 'Слива',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Слива',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка азотом',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Мочевина',
    priority: 'HIGH',
  },
  {
    speciesName: 'Слива',
    careType: 'FERTILIZE',
    title: 'Осенняя подкормка калием',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 9,
    fertilizerName: 'Калий сернокислый',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Слива',
    careType: 'PRUNE',
    title: 'Весенняя обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Слива',
    careType: 'SPRAY',
    title: 'Обработка от монилиоза',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 4,
    monthEnd: 7,
    treatmentName: 'Бордосская жидкость',
    priority: 'HIGH',
  },
  {
    speciesName: 'Слива',
    careType: 'SPRAY',
    title: 'Обработка от тли',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Слива',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },

  // =====================
  // ЧЕРЕШНЯ (Sweet cherry)
  // =====================
  {
    speciesName: 'Черешня',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 8,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Черешня',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Черешня',
    careType: 'FERTILIZE',
    title: 'Осенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 9,
    fertilizerName: 'Суперфосфат',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Черешня',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Черешня',
    careType: 'SPRAY',
    title: 'Обработка от коккомикоза',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 4,
    monthEnd: 6,
    treatmentName: 'Бордосская жидкость',
    priority: 'HIGH',
  },
  {
    speciesName: 'Черешня',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 7,
    priority: 'HIGH',
  },

  // =====================
  // АБРИКОС (Apricot)
  // =====================
  {
    speciesName: 'Абрикос',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Абрикос',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка азотом',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Мочевина',
    priority: 'HIGH',
  },
  {
    speciesName: 'Абрикос',
    careType: 'FERTILIZE',
    title: 'Подкормка фосфором после цветения',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 6,
    fertilizerName: 'Суперфосфат',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Абрикос',
    careType: 'PRUNE',
    title: 'Весенняя обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Абрикос',
    careType: 'SPRAY',
    title: 'Обработка от монилиоза',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 4,
    monthEnd: 6,
    treatmentName: 'Бордосская жидкость',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Абрикос',
    careType: 'SPRAY',
    title: 'Обработка от тли',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Абрикос',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 8,
    priority: 'HIGH',
  },

  // =====================
  // ПЕРСИК (Peach)
  // =====================
  {
    speciesName: 'Персик',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Персик',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка азотом',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    fertilizerName: 'Мочевина',
    priority: 'HIGH',
  },
  {
    speciesName: 'Персик',
    careType: 'FERTILIZE',
    title: 'Подкормка калием в период плодоношения',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Монофосфат калия',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Персик',
    careType: 'PRUNE',
    title: 'Весенняя обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Персик',
    careType: 'SPRAY',
    title: 'Обработка от курчавости листьев',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 3,
    monthEnd: 5,
    treatmentName: 'Медный купорос',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Персик',
    careType: 'SPRAY',
    title: 'Обработка от тли',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Персик',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },

  // =====================
  // АЛЫЧА (Cherry plum)
  // =====================
  {
    speciesName: 'Алыча',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Алыча',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Алыча',
    careType: 'FERTILIZE',
    title: 'Осенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 9,
    fertilizerName: 'Калий сернокислый',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Алыча',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Алыча',
    careType: 'SPRAY',
    title: 'Обработка от болезней',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 4,
    monthEnd: 7,
    treatmentName: 'Бордосская жидкость',
    priority: 'HIGH',
  },
  {
    speciesName: 'Алыча',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 8,
    priority: 'HIGH',
  },

  // =====================
  // ВИНОГРАД ТЕХНИЧЕСКИЙ (Wine grape)
  // =====================
  {
    speciesName: 'Виноград технический',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград технический',
    careType: 'FERTILIZE',
    title: 'Подкормка весенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Виноград технический',
    careType: 'FERTILIZE',
    title: 'Подкормка в период созревания',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Монофосфат калия',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград технический',
    careType: 'PRUNE',
    title: 'Обрезка осенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Виноград технический',
    careType: 'PRUNE',
    title: 'Чеканка побегов',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 8,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград технический',
    careType: 'SPRAY',
    title: 'Обработка от милдью',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Бордосская жидкость',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Виноград технический',
    careType: 'SPRAY',
    title: 'Обработка от оидиума',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Топаз',
    priority: 'HIGH',
  },
  {
    speciesName: 'Виноград технический',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 10,
    priority: 'HIGH',
  },

  // =====================
  // ВИНОГРАД КИШМИШ (Seedless grape)
  // =====================
  {
    speciesName: 'Виноград кишмиш',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград кишмиш',
    careType: 'FERTILIZE',
    title: 'Подкормка весенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Виноград кишмиш',
    careType: 'FERTILIZE',
    title: 'Подкормка в период созревания',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Монофосфат калия',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград кишмиш',
    careType: 'PRUNE',
    title: 'Обрезка осенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Виноград кишмиш',
    careType: 'PRUNE',
    title: 'Чеканка побегов',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 8,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград кишмиш',
    careType: 'SPRAY',
    title: 'Обработка от милдью',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Бордосская жидкость',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Виноград кишмиш',
    careType: 'SPRAY',
    title: 'Обработка от оидиума',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Топаз',
    priority: 'HIGH',
  },
  {
    speciesName: 'Виноград кишмиш',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 10,
    priority: 'HIGH',
  },

  // =====================
  // ПЕРЕЦ СЛАДКИЙ (Sweet pepper)
  // =====================
  {
    speciesName: 'Перец сладкий',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 6,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Перец сладкий',
    careType: 'FERTILIZE',
    title: 'Подкормка комплексная',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Перец сладкий',
    careType: 'FERTILIZE',
    title: 'Подкормка калием в период плодоношения',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 9,
    fertilizerName: 'Монофосфат калия',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Перец сладкий',
    careType: 'SPRAY',
    title: 'Обработка от тли',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 8,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Перец сладкий',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Перец сладкий',
    careType: 'PLANT',
    title: 'Посев на рассаду',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 2,
    monthEnd: 2,
    priority: 'CRITICAL',
  },

  // =====================
  // БАКЛАЖАН (Eggplant)
  // =====================
  {
    speciesName: 'Баклажан',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 6,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Баклажан',
    careType: 'FERTILIZE',
    title: 'Подкормка комплексная',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Баклажан',
    careType: 'SPRAY',
    title: 'Обработка от колорадского жука',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    treatmentName: 'Актара',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Баклажан',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Баклажан',
    careType: 'PLANT',
    title: 'Посев на рассаду',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 2,
    monthEnd: 2,
    priority: 'CRITICAL',
  },

  // =====================
  // МОРКОВЬ (Carrot)
  // =====================
  {
    speciesName: 'Морковь',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Морковь',
    careType: 'FERTILIZE',
    title: 'Подкормка при посеве',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Морковь',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Морковь',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'HIGH',
  },

  // =====================
  // СВЁКЛА (Beetroot)
  // =====================
  {
    speciesName: 'Свёкла',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Свёкла',
    careType: 'FERTILIZE',
    title: 'Подкормка при посеве',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Свёкла',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Свёкла',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'HIGH',
  },

  // =====================
  // КАПУСТА БЕЛОКОЧАННАЯ (Cabbage)
  // =====================
  {
    speciesName: 'Капуста белокочанная',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 5,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Капуста белокочанная',
    careType: 'FERTILIZE',
    title: 'Подкормка азотом после высадки',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 6,
    fertilizerName: 'Мочевина',
    priority: 'HIGH',
  },
  {
    speciesName: 'Капуста белокочанная',
    careType: 'FERTILIZE',
    title: 'Подкормка комплексная при завязывании кочана',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Капуста белокочанная',
    careType: 'SPRAY',
    title: 'Обработка от гусениц',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    treatmentName: 'Фитоверм',
    priority: 'HIGH',
  },
  {
    speciesName: 'Капуста белокочанная',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Капуста белокочанная',
    careType: 'PLANT',
    title: 'Посев на рассаду',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },

  // =====================
  // ЛУК РЕПЧАТЫЙ (Onion)
  // =====================
  {
    speciesName: 'Лук репчатый',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Лук репчатый',
    careType: 'FERTILIZE',
    title: 'Подкормка азотом',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    fertilizerName: 'Мочевина',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Лук репчатый',
    careType: 'FERTILIZE',
    title: 'Подкормка фосфорно-калийная',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 6,
    fertilizerName: 'Суперфосфат',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Лук репчатый',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 8,
    priority: 'HIGH',
  },
  {
    speciesName: 'Лук репчатый',
    careType: 'PLANT',
    title: 'Посадка севка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'HIGH',
  },

  // =====================
  // ЧЕСНОК (Garlic)
  // =====================
  {
    speciesName: 'Чеснок',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Чеснок',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка азотом',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Мочевина',
    priority: 'HIGH',
  },
  {
    speciesName: 'Чеснок',
    careType: 'FERTILIZE',
    title: 'Подкормка калием',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 6,
    fertilizerName: 'Калий сернокислый',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Чеснок',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 8,
    priority: 'HIGH',
  },
  {
    speciesName: 'Чеснок',
    careType: 'PLANT',
    title: 'Посадка озимого чеснока',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'HIGH',
  },

  // =====================
  // КАБАЧОК (Zucchini)
  // =====================
  {
    speciesName: 'Кабачок',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 6,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Кабачок',
    careType: 'FERTILIZE',
    title: 'Подкормка органическая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 6,
    fertilizerName: 'Компост',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Кабачок',
    careType: 'FERTILIZE',
    title: 'Подкормка комплексная в период плодоношения',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 8,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Кабачок',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Кабачок',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'HIGH',
  },

  // =====================
  // ТЫКВА (Pumpkin)
  // =====================
  {
    speciesName: 'Тыква',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Тыква',
    careType: 'FERTILIZE',
    title: 'Подкормка органическая при посадке',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    fertilizerName: 'Перегной',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Тыква',
    careType: 'FERTILIZE',
    title: 'Подкормка в период роста плодов',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 8,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Тыква',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Тыква',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'HIGH',
  },

  // =====================
  // ГОРОХ (Peas)
  // =====================
  {
    speciesName: 'Горох',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Горох',
    careType: 'FERTILIZE',
    title: 'Подкормка фосфорно-калийная',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 6,
    fertilizerName: 'Суперфосфат',
    priority: 'LOW',
  },
  {
    speciesName: 'Горох',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 8,
    priority: 'HIGH',
  },
  {
    speciesName: 'Горох',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 5,
    priority: 'HIGH',
  },

  // =====================
  // ФАСОЛЬ (Beans)
  // =====================
  {
    speciesName: 'Фасоль',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Фасоль',
    careType: 'FERTILIZE',
    title: 'Подкормка фосфорно-калийная',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Суперфосфат',
    priority: 'LOW',
  },
  {
    speciesName: 'Фасоль',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Фасоль',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 6,
    priority: 'HIGH',
  },

  // =====================
  // РЕДИС (Radish)
  // =====================
  {
    speciesName: 'Редис',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 4,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Редис',
    careType: 'FERTILIZE',
    title: 'Подкормка при посеве',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'LOW',
  },
  {
    speciesName: 'Редис',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Редис',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 8,
    priority: 'MEDIUM',
  },

  // =====================
  // ЕЖЕВИКА (Blackberry)
  // =====================
  {
    speciesName: 'Ежевика',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Ежевика',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Перегной',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Ежевика',
    careType: 'FERTILIZE',
    title: 'Подкормка в период плодоношения',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Монофосфат калия',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Ежевика',
    careType: 'PRUNE',
    title: 'Обрезка отплодоносивших побегов',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Ежевика',
    careType: 'SPRAY',
    title: 'Обработка от вредителей',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Ежевика',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },

  // =====================
  // ГОЛУБИКА (Blueberry)
  // =====================
  {
    speciesName: 'Голубика',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 5,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Голубика',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Калий сернокислый',
    priority: 'HIGH',
  },
  {
    speciesName: 'Голубика',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Голубика',
    careType: 'SPRAY',
    title: 'Обработка от болезней',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Фитоспорин-М',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Голубика',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 8,
    priority: 'HIGH',
  },

  // =====================
  // ЖИМОЛОСТЬ (Honeysuckle)
  // =====================
  {
    speciesName: 'Жимолость',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Жимолость',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Жимолость',
    careType: 'PRUNE',
    title: 'Осенняя обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Жимолость',
    careType: 'SPRAY',
    title: 'Обработка от тли',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 6,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Жимолость',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 6,
    priority: 'HIGH',
  },

  // =====================
  // СМОРОДИНА КРАСНАЯ (Red currant)
  // =====================
  {
    speciesName: 'Смородина красная',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Смородина красная',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Смородина красная',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Смородина красная',
    careType: 'SPRAY',
    title: 'Обработка от клеща',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 6,
    treatmentName: 'Фитоверм',
    priority: 'HIGH',
  },
  {
    speciesName: 'Смородина красная',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    priority: 'HIGH',
  },

  // =====================
  // КРЫЖОВНИК (Gooseberry)
  // =====================
  {
    speciesName: 'Крыжовник',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Крыжовник',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Крыжовник',
    careType: 'FERTILIZE',
    title: 'Осенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 9,
    fertilizerName: 'Калий сернокислый',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Крыжовник',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Крыжовник',
    careType: 'SPRAY',
    title: 'Обработка от мучнистой росы',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Топаз',
    priority: 'HIGH',
  },
  {
    speciesName: 'Крыжовник',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 8,
    priority: 'HIGH',
  },

  // =====================
  // ОБЛЕПИХА (Sea buckthorn)
  // =====================
  {
    speciesName: 'Облепиха',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'LOW',
  },
  {
    speciesName: 'Облепиха',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'LOW',
  },
  {
    speciesName: 'Облепиха',
    careType: 'PRUNE',
    title: 'Санитарная обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Облепиха',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 9,
    priority: 'HIGH',
  },

  // =====================
  // КАЛИНА (Viburnum)
  // =====================
  {
    speciesName: 'Калина',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'LOW',
  },
  {
    speciesName: 'Калина',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'LOW',
  },
  {
    speciesName: 'Калина',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Калина',
    careType: 'SPRAY',
    title: 'Обработка от листоеда',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Актара',
    priority: 'HIGH',
  },
  {
    speciesName: 'Калина',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 10,
    priority: 'MEDIUM',
  },

  // =====================
  // УКРОП (Dill)
  // =====================
  {
    speciesName: 'Укроп',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Укроп',
    careType: 'FERTILIZE',
    title: 'Подкормка при посеве',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'LOW',
  },
  {
    speciesName: 'Укроп',
    careType: 'HARVEST',
    title: 'Срезка зелени',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Укроп',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 8,
    priority: 'MEDIUM',
  },

  // =====================
  // ПЕТРУШКА (Parsley)
  // =====================
  {
    speciesName: 'Петрушка',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Петрушка',
    careType: 'FERTILIZE',
    title: 'Подкормка при посеве',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'LOW',
  },
  {
    speciesName: 'Петрушка',
    careType: 'HARVEST',
    title: 'Срезка зелени',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Петрушка',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    priority: 'MEDIUM',
  },

  // =====================
  // БАЗИЛИК (Basil)
  // =====================
  {
    speciesName: 'Базилик',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Базилик',
    careType: 'FERTILIZE',
    title: 'Подкормка после срезки',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 8,
    fertilizerName: 'Мочевина',
    priority: 'LOW',
  },
  {
    speciesName: 'Базилик',
    careType: 'HARVEST',
    title: 'Срезка зелени',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Базилик',
    careType: 'PLANT',
    title: 'Посев на рассаду',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    priority: 'HIGH',
  },

  // =====================
  // МЯТА (Mint)
  // =====================
  {
    speciesName: 'Мята',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Мята',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'LOW',
  },
  {
    speciesName: 'Мята',
    careType: 'HARVEST',
    title: 'Срезка зелени',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Мята',
    careType: 'PLANT',
    title: 'Посадка делёнками',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'MEDIUM',
  },

  // =====================
  // КИНЗА (Coriander)
  // =====================
  {
    speciesName: 'Кинза',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Кинза',
    careType: 'FERTILIZE',
    title: 'Подкормка при посеве',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'LOW',
  },
  {
    speciesName: 'Кинза',
    careType: 'HARVEST',
    title: 'Срезка зелени',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Кинза',
    careType: 'PLANT',
    title: 'Посев в открытый грунт',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 7,
    priority: 'MEDIUM',
  },
];
