export interface CareTemplateSeed {
  speciesName: string;
  careType: string;
  title: string;
  rrule: string;
  monthStart: number;
  monthEnd: number;
  fertilizerName?: string;
  treatmentName?: string;
  priority: string;
}

export const careTemplates: CareTemplateSeed[] = [
  // =====================
  // ЯБЛОНЯ (Apple tree)
  // =====================
  {
    speciesName: 'Яблоня',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Яблоня',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка азотом',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    fertilizerName: 'Мочевина',
    priority: 'HIGH',
  },
  {
    speciesName: 'Яблоня',
    careType: 'FERTILIZE',
    title: 'Подкормка фосфором',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 6,
    fertilizerName: 'Суперфосфат',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Яблоня',
    careType: 'FERTILIZE',
    title: 'Осенняя подкормка калием',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 9,
    fertilizerName: 'Калий сернокислый',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Яблоня',
    careType: 'PRUNE',
    title: 'Весенняя обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Яблоня',
    careType: 'SPRAY',
    title: 'Обработка от парши',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 4,
    monthEnd: 7,
    treatmentName: 'Бордосская жидкость',
    priority: 'HIGH',
  },
  {
    speciesName: 'Яблоня',
    careType: 'SPRAY',
    title: 'Обработка от тли',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Яблоня',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 10,
    priority: 'HIGH',
  },

  // =====================
  // ГРУША (Pear)
  // =====================
  {
    speciesName: 'Груша',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Груша',
    careType: 'FERTILIZE',
    title: 'Весенняя подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Груша',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Груша',
    careType: 'SPRAY',
    title: 'Обработка от болезней',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 7,
    treatmentName: 'Медный купорос',
    priority: 'HIGH',
  },
  {
    speciesName: 'Груша',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 10,
    priority: 'HIGH',
  },

  // =====================
  // ВИШНЯ (Cherry)
  // =====================
  {
    speciesName: 'Вишня',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 8,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Вишня',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Вишня',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'HIGH',
  },
  {
    speciesName: 'Вишня',
    careType: 'SPRAY',
    title: 'Обработка от коккомикоза',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Бордосская жидкость',
    priority: 'HIGH',
  },
  {
    speciesName: 'Вишня',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 7,
    priority: 'HIGH',
  },

  // =====================
  // ТОМАТ (Tomato)
  // =====================
  {
    speciesName: 'Томат',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 6,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Томат',
    careType: 'FERTILIZE',
    title: 'Подкормка комплексная',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Томат',
    careType: 'FERTILIZE',
    title: 'Подкормка калием',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 9,
    fertilizerName: 'Монофосфат калия',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Томат',
    careType: 'PRUNE',
    title: 'Пасынкование',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 8,
    priority: 'HIGH',
  },
  {
    speciesName: 'Томат',
    careType: 'SPRAY',
    title: 'Обработка от фитофтороза',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    treatmentName: 'Фитоспорин-М',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Томат',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Томат',
    careType: 'PLANT',
    title: 'Посев на рассаду',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 3,
    monthEnd: 3,
    priority: 'CRITICAL',
  },

  // =====================
  // ОГУРЕЦ (Cucumber)
  // =====================
  {
    speciesName: 'Огурец',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Огурец',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Огурец',
    careType: 'SPRAY',
    title: 'Обработка от болезней',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    treatmentName: 'Фитоспорин-М',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Огурец',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Огурец',
    careType: 'PLANT',
    title: 'Посев',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'HIGH',
  },

  // =====================
  // КАРТОФЕЛЬ (Potato)
  // =====================
  {
    speciesName: 'Картофель',
    careType: 'PRUNE',
    title: 'Окучивание',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 7,
    priority: 'HIGH',
  },
  {
    speciesName: 'Картофель',
    careType: 'SPRAY',
    title: 'Обработка от колорадского жука',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 8,
    treatmentName: 'Актара',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Картофель',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    fertilizerName: 'Нитроаммофоска',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Картофель',
    careType: 'PLANT',
    title: 'Посадка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 5,
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Картофель',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 9,
    priority: 'HIGH',
  },

  // =====================
  // КЛУБНИКА (Strawberry)
  // =====================
  {
    speciesName: 'Клубника',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=DAILY;INTERVAL=3',
    monthStart: 5,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Клубника',
    careType: 'FERTILIZE',
    title: 'Подкормка весенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Клубника',
    careType: 'FERTILIZE',
    title: 'Подкормка после плодоношения',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Суперфосфат',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Клубника',
    careType: 'SPRAY',
    title: 'Обработка от серой гнили',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 6,
    treatmentName: 'Фитоспорин-М',
    priority: 'HIGH',
  },
  {
    speciesName: 'Клубника',
    careType: 'PRUNE',
    title: 'Обрезка усов',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 6,
    monthEnd: 8,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Клубника',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 6,
    monthEnd: 7,
    priority: 'HIGH',
  },

  // =====================
  // СМОРОДИНА ЧЁРНАЯ (Black currant)
  // =====================
  {
    speciesName: 'Смородина чёрная',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Смородина чёрная',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Компост',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Смородина чёрная',
    careType: 'PRUNE',
    title: 'Обрезка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'HIGH',
  },
  {
    speciesName: 'Смородина чёрная',
    careType: 'SPRAY',
    title: 'Обработка от клеща',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 6,
    treatmentName: 'Фитоверм',
    priority: 'HIGH',
  },
  {
    speciesName: 'Смородина чёрная',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    priority: 'HIGH',
  },

  // =====================
  // ВИНОГРАД СТОЛОВЫЙ (Table grape)
  // =====================
  {
    speciesName: 'Виноград столовый',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'FERTILIZE',
    title: 'Подкормка весенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Нитроаммофоска',
    priority: 'HIGH',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'FERTILIZE',
    title: 'Подкормка в период созревания',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 7,
    monthEnd: 7,
    fertilizerName: 'Монофосфат калия',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'PRUNE',
    title: 'Обрезка осенняя',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 10,
    monthEnd: 10,
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'PRUNE',
    title: 'Чеканка побегов',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 8,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'SPRAY',
    title: 'Обработка от милдью',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Бордосская жидкость',
    priority: 'CRITICAL',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'SPRAY',
    title: 'Обработка от оидиума',
    rrule: 'FREQ=WEEKLY;INTERVAL=2',
    monthStart: 5,
    monthEnd: 8,
    treatmentName: 'Топаз',
    priority: 'HIGH',
  },
  {
    speciesName: 'Виноград столовый',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 8,
    monthEnd: 10,
    priority: 'HIGH',
  },

  // =====================
  // МАЛИНА (Raspberry)
  // =====================
  {
    speciesName: 'Малина',
    careType: 'WATER',
    title: 'Полив',
    rrule: 'FREQ=WEEKLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 9,
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Малина',
    careType: 'FERTILIZE',
    title: 'Подкормка',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 4,
    monthEnd: 4,
    fertilizerName: 'Перегной',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Малина',
    careType: 'PRUNE',
    title: 'Обрезка отплодоносивших побегов',
    rrule: 'FREQ=YEARLY;INTERVAL=1',
    monthStart: 9,
    monthEnd: 9,
    priority: 'HIGH',
  },
  {
    speciesName: 'Малина',
    careType: 'SPRAY',
    title: 'Обработка от вредителей',
    rrule: 'FREQ=MONTHLY;INTERVAL=1',
    monthStart: 5,
    monthEnd: 7,
    treatmentName: 'Фитоверм',
    priority: 'MEDIUM',
  },
  {
    speciesName: 'Малина',
    careType: 'HARVEST',
    title: 'Сбор урожая',
    rrule: 'FREQ=DAILY;INTERVAL=2',
    monthStart: 7,
    monthEnd: 8,
    priority: 'HIGH',
  },
];
