export const fertilizers = [
  // Минеральные
  {
    name: 'Мочевина',
    type: 'mineral',
    nitrogenN: 46,
    phosphorusP: 0,
    potassiumK: 0,
    applicationRate: '20-30 г/м²',
  },
  {
    name: 'Аммиачная селитра',
    type: 'mineral',
    nitrogenN: 34,
    phosphorusP: 0,
    potassiumK: 0,
    applicationRate: '15-25 г/м²',
  },
  {
    name: 'Суперфосфат',
    type: 'mineral',
    nitrogenN: 0,
    phosphorusP: 20,
    potassiumK: 0,
    applicationRate: '30-50 г/м²',
  },
  {
    name: 'Двойной суперфосфат',
    type: 'mineral',
    nitrogenN: 0,
    phosphorusP: 46,
    potassiumK: 0,
    applicationRate: '15-25 г/м²',
  },
  {
    name: 'Калий хлористый',
    type: 'mineral',
    nitrogenN: 0,
    phosphorusP: 0,
    potassiumK: 60,
    applicationRate: '15-20 г/м²',
  },
  {
    name: 'Калий сернокислый',
    type: 'mineral',
    nitrogenN: 0,
    phosphorusP: 0,
    potassiumK: 50,
    applicationRate: '20-30 г/м²',
  },
  // Комплексные
  {
    name: 'Нитроаммофоска',
    type: 'complex',
    nitrogenN: 16,
    phosphorusP: 16,
    potassiumK: 16,
    applicationRate: '30-50 г/м²',
  },
  {
    name: 'Диаммофоска',
    type: 'complex',
    nitrogenN: 10,
    phosphorusP: 26,
    potassiumK: 26,
    applicationRate: '20-30 г/м²',
  },
  {
    name: 'Азофоска',
    type: 'complex',
    nitrogenN: 16,
    phosphorusP: 16,
    potassiumK: 16,
    applicationRate: '30-50 г/м²',
  },
  {
    name: 'Монофосфат калия',
    type: 'complex',
    nitrogenN: 0,
    phosphorusP: 52,
    potassiumK: 34,
    applicationRate: '10-15 г на 10 л воды',
  },
  // Органические
  {
    name: 'Компост',
    type: 'organic',
    nitrogenN: 1,
    phosphorusP: 0.5,
    potassiumK: 1,
    applicationRate: '5-8 кг/м²',
  },
  {
    name: 'Перегной',
    type: 'organic',
    nitrogenN: 0.5,
    phosphorusP: 0.3,
    potassiumK: 0.6,
    applicationRate: '4-6 кг/м²',
  },
  {
    name: 'Зола древесная',
    type: 'organic',
    nitrogenN: 0,
    phosphorusP: 3,
    potassiumK: 8,
    applicationRate: '100-200 г/м²',
  },
  {
    name: 'Костная мука',
    type: 'organic',
    nitrogenN: 1,
    phosphorusP: 15,
    potassiumK: 0,
    applicationRate: '100-200 г/м²',
  },
  {
    name: 'Биогумус',
    type: 'organic',
    nitrogenN: 2,
    phosphorusP: 1.5,
    potassiumK: 1.5,
    applicationRate: '3-5 кг/м²',
  },
  {
    name: 'Навоз коровий',
    type: 'organic',
    nitrogenN: 0.5,
    phosphorusP: 0.25,
    potassiumK: 0.6,
    applicationRate: '5-8 кг/м²',
  },
];
