export const treatments = [
  // Химические
  {
    name: 'Бордосская жидкость',
    type: 'chemical',
    activeIngredient: 'медь (сульфат меди + гидроксид кальция)',
    targetPests: '',
    targetDiseases: 'Парша, монилиоз, милдью, пероноспороз, фитофтороз, антракноз, септориоз',
    dosage: '1% раствор — 100 г медного купороса + 100 г извести на 10 л воды; 3% — для ранневесенней обработки',
    safetyPeriodDays: 15,
  },
  {
    name: 'Медный купорос',
    type: 'chemical',
    activeIngredient: 'сульфат меди (CuSO₄)',
    targetPests: '',
    targetDiseases: 'Парша, монилиоз, коккомикоз, клястероспориоз, антракноз, бактериальный рак',
    dosage: '50-100 г на 10 л воды',
    safetyPeriodDays: 20,
  },
  {
    name: 'Железный купорос',
    type: 'chemical',
    activeIngredient: 'сульфат железа (FeSO₄)',
    targetPests: '',
    targetDiseases: 'Мхи, лишайники, хлороз, парша, чёрный рак, цитоспороз',
    dosage: '300-500 г на 10 л воды (искореняющая обработка)',
    safetyPeriodDays: 14,
  },
  {
    name: 'Фундазол',
    type: 'chemical',
    activeIngredient: 'беномил',
    targetPests: '',
    targetDiseases: 'Мучнистая роса, серая гниль, фузариоз, фитофтороз, церкоспороз, вертициллёз',
    dosage: '10 г на 10 л воды',
    safetyPeriodDays: 20,
  },
  {
    name: 'Топаз',
    type: 'chemical',
    activeIngredient: 'пенконазол',
    targetPests: '',
    targetDiseases: 'Мучнистая роса, оидиум, ржавчина',
    dosage: '2 мл на 10 л воды',
    safetyPeriodDays: 14,
  },
  {
    name: 'Актара',
    type: 'chemical',
    activeIngredient: 'тиаметоксам',
    targetPests: 'Тля, белокрылка, колорадский жук, трипсы, щитовка',
    targetDiseases: '',
    dosage: '1-2 г на 10 л воды (полив), 4 г на 10 л (опрыскивание)',
    safetyPeriodDays: 21,
  },
  {
    name: 'Карбофос',
    type: 'chemical',
    activeIngredient: 'малатион',
    targetPests: 'Тля, клещи, плодожорка, долгоносик, пилильщик, белокрылка, щитовка',
    targetDiseases: '',
    dosage: '60 г на 10 л воды',
    safetyPeriodDays: 20,
  },
  {
    name: 'Децис Профи',
    type: 'chemical',
    activeIngredient: 'дельтаметрин',
    targetPests: 'Плодожорка, листовёртка, тля, колорадский жук, крестоцветная блошка',
    targetDiseases: '',
    dosage: '0.5-1 г на 10 л воды',
    safetyPeriodDays: 20,
  },
  // Биологические
  {
    name: 'Фитоспорин-М',
    type: 'biological',
    activeIngredient: 'Bacillus subtilis (штамм 26Д)',
    targetPests: '',
    targetDiseases: 'Фитофтороз, мучнистая роса, парша, ржавчина, корневые гнили, чёрная ножка, серая гниль',
    dosage: 'Паста: 200 г на 400 мл воды (маточный раствор), 1 ст. л. на 10 л воды',
    safetyPeriodDays: null,
  },
  {
    name: 'Триходермин',
    type: 'biological',
    activeIngredient: 'Trichoderma harzianum',
    targetPests: '',
    targetDiseases: 'Корневые гнили, фузариоз, фитофтороз, белая и серая гниль',
    dosage: '20 г на 10 л воды (полив), 20 г на 5 л воды (опрыскивание)',
    safetyPeriodDays: null,
  },
  {
    name: 'Битоксибациллин',
    type: 'biological',
    activeIngredient: 'Bacillus thuringiensis var. thuringiensis',
    targetPests: 'Колорадский жук, гусеницы белянки, плодожорка, листовёртка, паутинный клещ',
    targetDiseases: '',
    dosage: '40-100 мл на 10 л воды',
    safetyPeriodDays: 5,
  },
  {
    name: 'Лепидоцид',
    type: 'biological',
    activeIngredient: 'Bacillus thuringiensis var. kurstaki',
    targetPests: 'Гусеницы: капустная белянка, плодожорка, листовёртка, моль, пяденица',
    targetDiseases: '',
    dosage: '20-30 мл на 10 л воды',
    safetyPeriodDays: 5,
  },
  {
    name: 'Фитоверм',
    type: 'biological',
    activeIngredient: 'аверсектин С',
    targetPests: 'Тля, паутинный клещ, трипсы, белокрылка, плодожорка',
    targetDiseases: '',
    dosage: '2-4 мл на 1 л воды',
    safetyPeriodDays: 3,
  },
  // Народные средства
  {
    name: 'Настой чеснока',
    type: 'folk',
    activeIngredient: 'аллицин, фитонциды',
    targetPests: 'Тля, паутинный клещ, трипсы, белокрылка',
    targetDiseases: 'Фитофтороз, мучнистая роса, ржавчина',
    dosage: '200 г измельчённого чеснока на 10 л воды, настаивать 24 часа',
    safetyPeriodDays: null,
  },
  {
    name: 'Мыльный раствор',
    type: 'folk',
    activeIngredient: 'жирные кислоты (хозяйственное мыло)',
    targetPests: 'Тля, паутинный клещ, белокрылка',
    targetDiseases: '',
    dosage: '200-300 г хозяйственного мыла на 10 л тёплой воды',
    safetyPeriodDays: null,
  },
  {
    name: 'Табачная пыль',
    type: 'folk',
    activeIngredient: 'никотин',
    targetPests: 'Тля, крестоцветная блошка, луковая муха, морковная муха, трипсы',
    targetDiseases: '',
    dosage: 'Опудривание или настой: 400 г на 10 л воды, настаивать 2 суток',
    safetyPeriodDays: null,
  },
  {
    name: 'Настой луковой шелухи',
    type: 'folk',
    activeIngredient: 'кверцетин, фитонциды',
    targetPests: 'Тля, паутинный клещ, трипсы',
    targetDiseases: 'Мучнистая роса, бактериозы',
    dosage: '200 г шелухи на 10 л кипятка, настаивать 12-15 часов',
    safetyPeriodDays: null,
  },
];
